version: "3"

service:
    app:
        build: .
        ports:
            - "3000:3000"
        links:
            - redis
            - mongo
        command: yarn start
        volumes:
          - ".:/usr/app"
    mongo:
        container_name: mongo
        image: 'mongo'
        ports:
          - "27017:27017"
    redis:
        container_name: redis
        image: 'redis:alpine'
        ports:
          - "6379:6379"
